# Generated by Django 4.0.1 on 2022-06-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Rut',
            new_name='rut',
        ),
        migrations.AddField(
            model_name='items_carrito',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
