# Generated by Django 4.0.1 on 2022-06-22 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_suscripcion_rename_apellido_usuarios_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suscripcion',
            table='db_suscripcion',
        ),
    ]
