# Generated by Django 4.0.1 on 2022-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_suscripcion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_carrito',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
