# Generated by Django 4.0.1 on 2022-06-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_items_carrito_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=40)),
                ('precio_producto', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'db_historial',
            },
        ),
    ]
