# Generated by Django 4.0.1 on 2022-06-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_historial_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
    ]
