# Generated by Django 4.0.1 on 2022-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_suscripcion_suscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='suscrito',
            field=models.BooleanField(),
        ),
    ]
