# Generated by Django 4.0.1 on 2022-06-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_suscripcion_suscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='suscrito',
            field=models.BooleanField(default=True),
        ),
    ]
